FROM ubuntu:latest

MAINTAINER Richard Attermeyer <richard.attermeyer@gmail.com>

RUN apt-get update \
  && apt-get -y upgrade \
  && apt-get -y autoclean \
  && apt-get -y autoremove \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

